version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: free-crm
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: