version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: freecrm-postgres-master-node
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: free-crm
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-read-replica:
    image: postgres:15
    container_name: freecrm-postgres-read-replica
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: free-crm
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: freecrm-redis
    image: redis:alpine3.19
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    expose:
      - "6379"

volumes:
  postgres_data: