spring:
  jpa:
    open-in-view: false
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: true
  liquibase:
    enabled: true
    change-log: "classpath:/db-changelog/changelog-master.xml"


master-datasource:
  url: jdbc:postgresql://localhost:5433/free-crm
  username: user
  password: password
  driver-class-name: org.postgresql.Driver
  configuration:
    pool-name: free-crm-master
readonly-datasource:
  url: jdbc:postgresql://localhost:5434/free-crm
  username: replicator
  password: replicator_password
  driver-class-name: org.postgresql.Driver
  configuration:
    pool-name: free-crm-slave