
spring:
  config:
    import: 'classpath:persistence.yaml'
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://nkumdhunlgcvfnqpcgpj.supabase.co/auth/v1/callback
          jws-algorithms: HS256